# Generated by Django 6.1 on 2026-09-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='album',
        ),
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('track_name', models.CharField(db_index=True, max_length=200)),
                ('artists', models.CharField(db_index=True, max_length=200)),
                ('album_name', models.CharField(blank=True, max_length=200, null=True)),
                ('popularity', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('explicit', models.BooleanField(default=False)),
                ('danceability', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('key', models.IntegerField(default=0)),
                ('loudness', models.FloatField(default=0)),
                ('mode', models.IntegerField(default=0)),
                ('speechiness', models.FloatField(default=0)),
                ('acousticness', models.FloatField(default=0)),
                ('instrumentalness', models.FloatField(default=0)),
                ('liveness', models.FloatField(default=0)),
                ('valence', models.FloatField(default=0)),
                ('tempo', models.FloatField(default=0)),
                ('time_signature', models.IntegerField(default=4)),
                ('track_genre', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spotify 歌曲',
                'verbose_name_plural': 'Spotify 歌曲',
                'db_table': 'spotify_track',
                'indexes': [models.Index(fields=['track_genre'], name='spotify_tra_track_g_fdab8f_idx'), models.Index(fields=['popularity'], name='spotify_tra_popular_dbbd06_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
