# Generated by Django 6.1 on 2026-09-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='artist_genre_idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='artist_idx',
            field=models.IntegerField(default=0),
        ),
    ]
