# Generated by Django 6.1 on 2026-09-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_userfeedback_artist_genre_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicKnowledge',
        ),
    ]
