# Generated by Django 6.1 on 2026-09-02 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_remove_comment_album_spotifytrack_delete_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.CharField(max_length=20, unique=True, verbose_name='豆瓣音乐ID')),
                ('title', models.CharField(max_length=200, verbose_name='专辑名称')),
                ('artist', models.CharField(max_length=100, verbose_name='歌手')),
                ('genre', models.CharField(blank=True, max_length=50, null=True, verbose_name='流派')),
                ('release_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='发行日期')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='评分')),
                ('rating_count', models.IntegerField(default=0, verbose_name='评分人数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论总数')),
            ],
            options={
                'verbose_name': '专辑信息',
                'verbose_name_plural': '专辑信息',
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=20, unique=True, verbose_name='评论ID')),
                ('user', models.CharField(max_length=100, verbose_name='用户昵称')),
                ('user_url', models.URLField(blank=True, null=True, verbose_name='用户主页')),
                ('rating', models.CharField(blank=True, max_length=10, null=True, verbose_name='用户评分（星数）')),
                ('comment_time', models.DateTimeField(blank=True, null=True, verbose_name='评论时间')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户所在地')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('useful', models.IntegerField(default=0, verbose_name='有用数')),
                ('is_truncated', models.BooleanField(default=False, verbose_name='是否被截断')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
                'db_table': 'comment',
            },
        ),
        migrations.RemoveIndex(
            model_name='spotifytrack',
            name='spotify_tra_track_g_fdab8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='spotifytrack',
            name='spotify_tra_popular_dbbd06_idx',
        ),
        migrations.DeleteModel(
            name='SpotifyTrack',
        ),
        migrations.AddField(
            model_name='comment',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webtest.album', verbose_name='所属专辑'),
        ),
    ]
